# Faye
development:
   server: "http://felipeconti.com.br:9292/faye"
   adapter_javascript_url: "http://felipeconti.com.br:9292/faye/faye.js"
   auth_token: felipeconti
   adapter: "Faye"
   async: true

# Pusher
# development:  
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
#   app_id: ENV["PUSHER_APP_ID"]
#   api_key: ENV["PUSHER_API_KEY"]
#   auth_token: ENV["PUSHER_SECRET"]
#   adapter: "Pusher"
#   async: true

test:
   server: "http://localhost:9292/faye"
   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
   adapter: "Faye"
   auth_token: "secret"
   async: false

production:
   server: "http://trip.felipeconti.com.br:9292/faye"
   adapter_javascript_url: "http://trip.felipeconti.com.br:9292/faye/faye.js"
   adapter: "Faye"
   auth_token: "d176c306c23892c3b822e4f71e2988361f6d0fea60e8e27bd665c6a2083f24c0"
   async: true
